export const posts = [
  {
    id: 1,
    title: "Understanding React Hooks",
    category: "Tech",
    image: "https://miro.medium.com/v2/1*jBsXkCIbVy9S_HuWOFfK7w.png",
    description: "Learn how useState and useEffect work in React.",
    date: "January 12, 2026",
  },
  {
    id: 2,
    title: "Exploring the Alps",
    category: "Travel",
    image: "https://picsum.photos/id/1018/600/400",
    description: "A breathtaking journey through the Alps.",
    date: "January 18, 2026",
  },
  {
    id: 3,
    title: "Best Pasta Recipes",
    category: "Food",
    image: "https://www.cookedandloved.com/wp-content/uploads/2025/10/chicken-pasta-recipes-feature.jpg",
    description: "Delicious pasta recipes you must try.",
    date: "January 20, 2026",
  },
  {
    id: 4,
    title: "Advanced JavaScript Patterns",
    category: "Tech",
    image: "https://www.go-globe.com/wp-content/uploads/2025/01/https___dev-to-uploads.s3.amazonaws.com_uploads_articles_rvjug6fy5trccggikkqk.webp",
    description: "Master closures, currying, and composition.",
    date: "January 22, 2026",
  },
  {
    id: 5,
    title: "Street Food in Thailand",
    category: "Food",
    image: "https://cdn.passporthealthusa.com/wp-content/uploads/2022/05/thailand-gluten-free.jpg?x34480",
    description: "Exploring Thailand's vibrant food culture.",
    date: "January 25, 2026",
  },
  {
    id: 6,
    title: "Backpacking South America",
    category: "Travel",
    image: "https://images.unsplash.com/photo-1543385426-191664295b58?q=80&w=995&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Budget travel tips across South America.",
    date: "January 28, 2026",
  },
  {
    id: 7,
    title: "Building REST APIs",
    category: "Tech",
    image: "https://petertheprogrammer.com/wp-content/uploads/2024/06/rest-api-php.jpg",
    description: "Design scalable backend APIs.",
    date: "February 1, 2026",
  },
  {
    id: 8,
    title: "Healthy Smoothie Ideas",
    category: "Food",
    image: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    description: "Quick and healthy smoothie recipes.",
    date: "February 5, 2026",
  }
];
